"""Add images table

Revision ID: 4909d4ff2b8e
Revises: 8b3d6e84792d
Create Date: 2025-09-27 14:17:56.362041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4909d4ff2b8e'
down_revision: Union[str, None] = '8b3d6e84792d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
